branch-defaults:
  addEmail:
    environment: docker-blacklist4
    group_suffix: null
  main:
    environment: Appbeanstalk2021-env
    group_suffix: null
environment-defaults:
  docker-blacklist4:
    branch: null
    repository: null
global:
  RootVolumeType: gp3
  application_name: docker-blacklist
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
